### ISSUE TITLE
OFFSET issue

### ISSUE THREAD

**Issue by gromiak** [vrana/notorm#10]
Hi, im trying to use your db management script, when I try to write paginator I discover some problems :

```
    $products = $this->db->product()->where('category_id = 2')->limit(3,3);
    echo get_class($products);
    foreach($products as $p) {
        echo $p['id'].' '.$p['name'].'<br />';
    }
```

This code outputs :

NotORM_Result
string 'SELECT \* FROM product WHERE (category_id = 2') LIMIT 3 OFFSET 3' (length=62)
5 ghgh
6 frgfrgt
7 multi photo

And this is working Just fine, but if I try another way like :
        $prod = $this->db->category[2]->product()->limit(3,3);
        echo get_class($prod);
        foreach($prod as $p) 
            echo $p['id'] . ' ' . $p['name'] . '<br />';

Im getting :

string 'SELECT \* FROM category WHERE (id = '2')' (length=39)
NotORM_MultiResult
string 'SELECT \* FROM product WHERE (product.category_id IN ('2')) LIMIT 3 OFFSET 3' (length=75)

and no data no errors nothing, I think where is some problem with offset because if I set ->limit(3) I'm getting data

**Comment by gromiak** [comment]
and im interested maybe there is the way to avoid wirst query in second example (above) ?

**Comment by vrana** [comment]
Please try the Git version, this bug was already fixed some time ago.

`$db->category[2]` queries the database, that's not gonna change.

**Comment by gromiak** [comment]
yeah my bad... with current version its work fine.
