### ISSUE TITLE
Fatal error where() with variable parameter

### ISSUE THREAD

**Issue by layanto** [vrana/notorm#100]
All the examples in notorm.com with where() having ?, the parameters supplied were all strings and not variables. When I tried to supply variable, I got PHP fatal error. 

Example from notorm.com
$table->where("field > ? AND field < ?", "x", "y")

With variables
$var1 = "x";
$var2 = "y";
$table->where("field > ? AND field < ?", $var1, $var2);

Fatal error
Parse Error: syntax error, unexpected '$var1' (T_VARIABLE)

What have I done wrong? Thanks.

**Comment by vrana** [comment]
You have probably some typo in the script, this is a PHP error, not NorORM's.

**Comment by layanto** [comment]
As NotORM is a php library then a PHP error can still be to do with NotORM. Not saying that this one is and maybe due to wrong usage of NotORM on my part.

->where("field > ?", "5"); //This works

$var = 5;
->where("field > ?", $var); //This does NOT work

$var = 5;
->where(" field > " . $var); //This works
