### ISSUE TITLE
Problem with composer

### ISSUE THREAD

**Issue by ainsofs** [vrana/notorm#106]
I try and install NotOrm using:
composer require vrana/notorm

But I get this error message
[InvalidArgumentException]  
  Could not find package softwarevamp/notorm at any version for your minimum-  
  stability (stable). Check the package spelling or your minimum-stability

**Comment by df-5** [comment]
`composer require vrana/notorm:dev-master`

**Comment by ainsofs** [comment]
Thank you. I was confused because the instructions on packagist.org use to use

composer require vrana/notorm

Perhaps the info can be updated. Cheers,
