### ISSUE TITLE
aggregation issue

### ISSUE THREAD

**Issue by gromiak** [vrana/notorm#11]
$pages = db->pagesdescription('pagesdescription.languages_id',1)->aggregation('pagesdescription.*,pages.user_id,pages.created');
var_dump($pages);
And this produces nice query, which works when I paste it to phpmyadmin, but var_dump returns string '1' (length=1)

**Comment by gromiak** [comment]
I guess the problem is in 430 line of NotORM/Result.php

**Comment by gromiak** [comment]
*****\* again im accidently closing ;/

**Comment by vrana** [comment]
The `aggregation` method is used for returning a single value like `aggregation('MAX(id)')`. I'm not sure what are you trying to achieve but look at the methods `select` and `group`.

P.S. Try [Adminer](http://www.adminer.org/) (my other PHP tool) instead of phpMyAdmin.

**Comment by gromiak** [comment]
hmm this code produces: 
SELECT pagesdescription.*,pages.user_id,pages.created FROM pagesdescription LEFT JOIN pages ON pagesdescription.pages_id = pages.id WHERE (pagesdescription.languages_id = 1)
whis is exactly what I wanted but var_dump returns 1 nothing else, is there any other way to do the same with results ?

**Comment by vrana** [comment]
Using `select` instead of `aggregation` should do the task. The `aggregation` method returns just the first column of the first row.

**Comment by gromiak** [comment]
ehh im circling around too much select works sorry for bother.
