### ISSUE TITLE
Set NotORM to PHP7 defaults.

### ISSUE THREAD

**Issue by efrj** [vrana/notorm#128]
Hi @vrana , Can I arrange to migrate NotORM to 100% compatible with PHP 7?
I really like NotORM and for a long time it was my favorite ORM. I really want to contribute to the project.

**Comment by WuJiY** [comment]
What's the situation now?

**Comment by vrana** [comment]
How's it incompatible? I'll accept a minimalistic patch fixing any issues. I probably wouldn't accept a major refactoring.
