### ISSUE TITLE
How create sub query inside SELECT, FROM, and JOIN?

### ISSUE THREAD

**Issue by adods** [vrana/notorm#13]
Just like the title, Can NotORM handle this?

**Comment by vrana** [comment]
FROM and JOIN is not possible, I'll consider SELECT.

**Comment by adods** [comment]
Then, Can i execute a custom query using NotORM? I mean if i have to load another library just to execute a custom query it feels like bloating the process

**Comment by vrana** [comment]
You don't have to load anything else. NotORM uses PDO so you can use NotORM for common (simple) queries and PDO for everything else.

**Comment by adods** [comment]
Is there a 'not where' function that generate something like: `name NOT IN (...)` or `field IS NOT NULL` or other `not` clause?

**Comment by vrana** [comment]
You can simply write `where("field IS NOT NULL")`. `NOT IN` can be written as `where("name NOT", array(1, 2))`.

**Comment by adods** [comment]
and how to use OR in where clause using NotORM?

**Comment by vrana** [comment]
`$table->where("a = ? OR b = ?", $a, $b)`

Support forum lives at http://groups.google.com/group/notorm

**Comment by vrana** [comment]
For subquery in SELECT, you can use `$db->table()->select("(" . $db->table2() . ") AS subquery")`.

**Comment by cevarief** [comment]
How could i exec plain query in NotORM and what is equivalent for LEFT OUTER JOIN ?

**Comment by vrana** [comment]
There's no need to exec plain query in NotORM. Use PDO instead. You usually don't need LEFT OUTER JOIN but you can use columns from referenced tables by dot notation. Read http://www.notorm.com/#api ("If the dot notation...").

**Comment by cevarief** [comment]


**Comment by cevarief** [comment]
I'm playing with the NotORM join sample with dot notation, bug get error. 

foreach ($this->db->application()->order("author.name, title") as $application) {
            echo $application->author["name"] . ": $application[title]\n";
}

Uncaught Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 In ..\notorm\Structure.php At Line 131

**Comment by vrana** [comment]
> What i want is to list authors who never been referenced as maintainer in application.

```
$maintainers = $software->application("maintainer_id IS NOT NULL")->select("maintainer_id");
foreach ($software->author("NOT id", $maintainers) as $author) {
}
```

**Comment by vrana** [comment]
> I'm playing with the NotORM join sample with dot notation, bug get error.

I have no problem with this query. Please update to the current Git version and enable debug to see the actual query.

**Comment by GaganTiwari** [comment]
@vrana I want to fetch single record but i m getting row:protected in my response.

`NotORM_Row Object
(
    [modified:NotORM_Row:private] => Array
        (
        )

```
[row:protected] => Array
    (
        [id] => 877
        [sku,quantity,name] => 
",1,""
            [ScriptID] => 0040360609160854190
            [FT] => HS21`
```

like this.

and my code is 

`$scripts_data = $db->Scripts()->where('ScriptID','0040360609160854190');
        $scripts_datas = $scripts_data->fetch();
        print_r($scripts_datas);`

can u help me immediately as i m too stucked with it. 

You can add your answer here 

http://www.askmedeveloper.com/question/how-create-sub-query-inside-select-from-and-join/

Thanks in advance
