### ISSUE TITLE
Is this project dead already ?

### ISSUE THREAD

**Issue by rizrmd** [vrana/notorm#133]

**Comment by vrana** [comment]
More or less.

**Comment by rizrmd** [comment]
So unfortunate, I found the syntax is so simple, yet powerful. 
May I know why did you decide to abandon it ? any alternative ?

**Comment by vrana** [comment]
I don't use it anymore. Try http://lessql.net/.

**Comment by jmorenovalde** [comment]
It's a pity. Thank you for your time.

**Comment by WuJiY** [comment]
It's a pity. Thank you for your time.
