### ISSUE TITLE
Suggestion: add a method to get the pdo connection.

### ISSUE THREAD

**Issue by shaybenmoshe** [vrana/notorm#14]
I think you should modify NotORM_Abstract class to let us get the pdo connection through it, so that we can use only the NotORM object even if we need to the pdo connection.

It should be something like that:

<pre>abstract class NotORM_Abstract {
    protected $connection, $driver, $structure, $cache;
    protected $notORM, $table, $primary, $rows, $referenced = array();
    
    protected $debug = false;
    protected $freeze = false;
    protected $rowClass = 'NotORM_Row';
    
    abstract protected function __construct();
    
    protected function access($key, $delete = false) {
    }
    
    /** Get PDO connection
    * @return PDO
    */
    function connection() {
        return $this->connection;
    }
    
}</pre>

By the way I love NotORM, thanks for creating it :)

Yours,
Shay Ben Moshe

**Comment by vrana** [comment]
`$notorm->connection()` is used for retrieving data from the table `connection`. NotORM constructor accepts PDO object so you can use this object for anything else.

**Comment by shaybenmoshe** [comment]
The thing is that with the current implementation you can call the connection table through either <code>$notorm->connection()</code> and <code>$notorm->connection</code>.
However you can't call the connection at all.
I think you should add a way to get the connection.
