### ISSUE TITLE
fails to quote column/table identifiers

### ISSUE THREAD

**Issue by mrclay** [vrana/notorm#15]
A generated query: `SELECT * FROM scrl_context WHERE (key = 'default');`
Fails because "key" is a reserved word and must be quoted: `key`

**Comment by mrclay** [comment]
(quoted with backticks)

**Comment by mrclay** [comment]
Ugh. PDO still has no quoteIdentifier(), so fixing this requires sniffing out the DB type from PDO.

**Comment by vrana** [comment]
This is a [documented behavior](http://www.notorm.com/#faq). You can quote the column name by yourself but the best approach is to avoid keywords in your identifiers.

**Comment by lkraider** [comment]
This does not work:

$table()->where('"select".name = ?', $name);
