### ISSUE TITLE
FetchPairs "a AS b"

### ISSUE THREAD

**Issue by sjurco** [vrana/notorm#16]
Zadany vyraz vrati prazdne pole v pripade, ze stlpec 'b' neexistuje.
V pripade ak existuje, vrati polia s hodnotami stlpcov 'b' a 'c', nie 'a' a 'c'.

```
$table->select('a AS b', 'c')->fetchPairs('b', 'c');
```

jedina moznost je zatial pisat

```
$table->select('a AS b', 'c')->fetchPairs('a AS b', 'c');
```

co mi ale pride ako zbytocne zdvojovanie kodu, najme pri zlozitejsich selectoch..

**Comment by vrana** [comment]
Metoda `fetchPairs` obsah `select` ignoruje. Stačí tedy psát `$table->fetchPairs('a', 'c')`.

**Comment by sjurco** [comment]
To je celkom rozumne :) Vdaka za odpoved

**Comment by stpnkcrk** [comment]
A co když chceme například v `$table->fetchPairs('id', 'name_with_function')` použít `AS name_with_function` výsledek funkce `CONCAT_WS`? Jde to nějak?

**Comment by vrana** [comment]
Identifikátor druhého parametru metody `fetchPairs` se na nic nepoužívá, takže je zbytečné mu dávat alias.
