### ISSUE TITLE
Getting a single row problem

### ISSUE THREAD

**Issue by ruzicka** [vrana/notorm#18]
Getting a single row
$application = $db->application[1]; // get by primary key
$application = $db->application("title = ?", "Adminer")->fetch();

První případ:
funguje jen když se primární klíč jmenuje "id". Vygenerovaný dotaz používá zatvrzele "id", i když se primární klíč jmenuje jinak.

Druhý případ:
$db->storage("name = ?", 'access_token')->fetch(); vygeneruje query "SELECT \* FROM storage WHERE (name = ?)" Otazník se tedy nenahradí.

**Comment by ruzicka** [comment]
Tak opravuji: Druhý případ funguje, otazník je v dotazu nahrazen. Není nahrazen jen v debug logu (volám přes callback funkci), kde je vše s otazníkama. To je ale taky docela problém.

K prvnímu problému ještě doplňuji, že kvůli tomu nefunguje ani update (mazání jsem nezkoušel). V logu vidím, že i v tomto případě to tam pořád cpe "id", i když se primární klíč jmenuje jinak.

**Comment by kubasimon** [comment]
Strukturu mas popsanou tady http://www.notorm.com/#api a tady http://www.notorm.com/#identifiers 
Defaultni tam mas popsanou, pokud pouzivas jinou, tak si to prepises.

V debugu, jak je popsane tady http://www.notorm.com/#api (prvni tabulka, druhy radek), dostane tvoje funkce dva parametry, $query a $parametrs

**Comment by ruzicka** [comment]
ááá, chápu. Díky za nasměrování, asi jsem měl lépe prostudovat dokumentaci, hledal jsem to ve špatné sekci.
