### ISSUE TITLE
Spatny pocet vysledku

### ISSUE THREAD

**Issue by Pitel** [vrana/notorm#19]
V projektu na ktereme delam mam za ukol provest portaci na NotORM, a hned pri prvni metode jsem narazil na podivne chovani.

Puvodni SQL prikaz je

``` sql
SELECT *, users.id as uid FROM users LEFT JOIN groups ON users.groups_id=groups.id WHERE gname<>'user';
```

ktery jsem prepsal na

``` php
$notorm->users()->select("*, users.id as uid")->where("groups.gname != 'user'");
```

Ten si podle ladiciho vystupu NotORM prevede na

``` sql
SELECT *, users.id as uid FROM users LEFT JOIN groups ON users.groups_id = groups.id WHERE (groups.gname != 'user');
```

coz je temer totozne s puvodnim prikazem.

Problem ale je, ze vrati jen 4 vysledky, zatimco v databazi jich je 7, viz screenshot z Adminera (loginy a hesla jsou zamerne zcenzurovany pomoci DOM editoru pred porizenim screenshotu):

![Screenshot z Adminera](http://dl.dropbox.com/u/1117903/sql.png)

Vracene radky jsou `ccc`, `eee`, `fff` a `ggg`, tedy  jako by posledni radky od kazdeho `groups_id` (nebo `gname`).

Vyzkouseno jak na verzi 2011-06-07 tak na aktualnim Gitu.

**Comment by vrana** [comment]
`groups.id` ve vráceném asociativním poli přepíše `users.id`. Doporučuji použít `->select("users.*")` a k tomu případně vše, co je potřeba z `groups`.

Dotaz by taky šel do NotORM přepsat víc. Já bych použil:

``` php
$notorm->users("groups_id", $notorm->groups("gname != ?", 'user'));
```
