### ISSUE TITLE
Multiple databases

### ISSUE THREAD

**Issue by cj** [vrana/notorm#20]
Hi,

Can notrom handle multiple databases?  If so, is there an example anywhere?

Many thanks

**Comment by vrana** [comment]
Please ask questions in [forum](http://groups.google.com/group/notorm).

What are you trying to achieve?

Basic support is available in MySQL through dot notation: `$notORM->{"db.table"}()` or:

``` php
$table = "db.table";
$notORM->$table();
```

**Comment by cj** [comment]
Sorry, didn't see there was a google group.  I get you, I'll try it out this weekend.  Thank you
