### ISSUE TITLE
No way to use limit in MSSQL on windows with php >= 5.3

### ISSUE THREAD

**Issue by wergio** [vrana/notorm#28]
Hi, unfortunately the DBLIB extension is not available anymore on Windows with PHP 5.3 or later. :-(
http://www.php.net/manual/en/ref.pdo-dblib.php

and the other two drivers avaiable doesn't accept NotORM's "limit" !!! Help !!!

example:

<pre>
require_once 'NotORM.php';

$pdo = new PDO("mssql:host=localhost,1433;dbname=notorm", 'sa', 'test');
//$pdo = new PDO("sqlsrv:Server=localhost;Database=notorm", 'sa', 'test'); // same behaviour
$db = new NotORM($pdo);

$articles= $db->article()->limit(2);

echo 'query: '.$articles."\n";
// query: SELECT * FROM article LIMIT 2 OFFSET 0

foreach($articles as $a)
 echo $a['title']."\n";

// nothing displayed...
</pre>

**Comment by wergio** [comment]
This seems to fix the problem:
wergio/notorm@ee792ee7533555b87b94b4e0dfb3d5c4f26bbbda

**Comment by vrana** [comment]
Merged, thanks.
