### ISSUE TITLE
logging of transactions

### ISSUE THREAD

**Issue by tomaswindsor** [vrana/notorm#30]
While the debug property can be used to log queries, there is no way to log the information that transaction has begun, has commited or that it has been rolled back.

**Comment by vrana** [comment]
What do you suggest? Please note that NotORM doesn't execute SQL commands for transactions but calls PDO methods `beginTransaction`, `commit` and `rollback` instead. So it doesn't know the actual commands executed. Current debug output can be used directly as SQL and it would be sad to miss this option.

**Comment by tomaswindsor** [comment]
I understand. Maybe it could log SQL comments such as:
-- beginTransaction call
-- commit call
-- rollback call
... it would still be of help.

**Comment by vrana** [comment]
This would be too difficult to implement as debugging is called inside Result and NotORM class doesn't have access to it.
