### ISSUE TITLE
select('field, table.*') - query ok but result is incomplete

### ISSUE THREAD

**Issue by xpavp03** [vrana/notorm#40]
Please have a look at this tests:
http://tmp.pepa.info/notorm/33-failing-join-group.phpt

It joins tables application and author and groups by title and author_id. The executed query is correct:
```SELECT title, author.\* 
FROM application 
LEFT JOIN author ON application.author_id = author.id 
GROUP BY title
ORDER BY title;

```

However, the result is not.
--FILE--
JUSH: Jakub Vrana
Nette: David Grudl
--EXPECTF--
Adminer: Jakub Vrana
Dibi: David Grudl
JUSH: Jakub Vrana
Nette: David Grudl

Edit: I just found out that the problem is in fact in select("title, author.*") and not in group() as I had though. I changed the ticket title to reflect it.

The test passes when I replace 'author.*' in the select() call with 'author_id' and use $row->author when printing the author name.
See here: http://tmp.pepa.info/notorm/33-working-join-group.phpt
```

**Comment by vrana** [comment]
NotORM stores data based on their primary key to allow working with relations. The query selects `author.id` instead of `application.id` which confuses NotORM. You can fix it by appending `application.id` to the query.

A better solution would be to use NotORM relations:

``` php
foreach ($software->application()->group("title")->order("title") as $application) {
  $author = $application->author;
}
```
