### ISSUE TITLE
Export of MySQL BIT values must be wrapped in quotes

### ISSUE THREAD

**Issue by xpavp03** [vrana/notorm#45]
MySQL: create table bit_test ( my_column BIT );

Values of my_column must be wrapped in quotes otherwise MySQL rejects the resulting dump with a syntax error message. Compare dump made with mysqldump and Adminer.

**Comment by vrana** [comment]
This is issue tracker for NotORM, not Adminer.

**Comment by xpavp03** [comment]
Sorry mate! Got it mixed up.
