### ISSUE TITLE
select top repeated values 

### ISSUE THREAD

**Issue by MotasemWaizr** [vrana/notorm#46]
Hello , I need some help please.
I need to select the most repeated value in a table!!! 
I thought that I can use order and count together but it doesn't work :S

**Comment by krky** [comment]
I didn't try but it should work.

$tags = $db->tag()->select('name, COUNT(name) as tcount')->order('tcount DESC')->group('name')->limit('1', '0');

**Comment by vrana** [comment]
Yes, it works.
