### ISSUE TITLE
Zaokrouhlování setin u čísel

### ISSUE THREAD

**Issue by xciza** [vrana/notorm#49]
Ahoj,
na webu tahám data do radiolistu pomocí následujícího kódu:
        $materials = $this->context->createMaterial()->fetchPairs('cena', 'nazev');

Problém je v tom, že cena v db je se setinami (např. 0.85) a po dumpnutí (zkontrolování) hodnot, které mají být v radiolistu jsou takovéto hodnoty zaokrouhleny na nulu. Desetinná místa (např. 0.9) to nikam nezaokrouhlí. 

Při výpisu dat z db je vše v pořádku a čísla mají normálně setiny.

Kde by prosím mohla být chyba?

**Comment by vrana** [comment]
Problém je nejspíš v tom, že z databáze lezou data jako float a PHP při pokusu o uložení `$a[0.85]` uloží prostě `$a[0]`. Vyřešil jsem to přetypováním na řetězec.
