### ISSUE TITLE
Counting problems

### ISSUE THREAD

**Issue by shaybenmoshe** [vrana/notorm#5]
Hi there, first of all I must say I LOVE NOTORM, it is just a great tool!
I found a little bug today when I was trying to count table's rows.
I have got table (lets name it A) referencing to table (lets name it B).
Now, when I am doing:
    foreach($db->B as $row) {
        echo $row->A->count('*');
    }
It gives an error when there are zero columns referencing to table B.
Even so, when I change it to count() (which is probably less efficient) it did work.

Hope that was helpful,
Shay

**Comment by vrana** [comment]
`$row->A` returns a single row or null if the row does not exist. If you want to get the number of rows pointing to your row, use `$row->A()->count("*")`.

**Comment by shaybenmoshe** [comment]
No, it still doesn't work.

It still gives me two errors in MultiResult.php on line 75:
Notice: Undefined index: 2
Warning: Invalid argument supplied for foreach()

And again, if I change it back from $row->A()->count('*') to $row->A()->count() it works perfectly fine.

Thank again,
Shay

**Comment by vrana** [comment]
Please explain the problem on the official example. The following code works perfect:

```
foreach ($software->author() as $author) {
    echo $author->application()->count("*") . "\n";
}
```
