### ISSUE TITLE
Composer autoload

### ISSUE THREAD

**Issue by lincolnbrito** [vrana/notorm#50]
I try to use NotORM with composer autoload but don't work. It use namespaces?

**Comment by jcambien** [comment]
The composer.json is incomplete actually.
It just let you load NotORM from Packagist, but the NotORM class structure is not PSR-0 compliant, so you have to load NotORM.php from your composer.json with the "files" clause in your root composer.json (see http://getcomposer.org/doc/04-schema.md#autoload). After this, NotORM will load others classes for you.

Example:

``` json
{
    "autoload": {
        "files": ["vendor/vrana/notorm/NotORM.php"]
    }
}
```

**Comment by lincolnbrito** [comment]
It Works!!! \0/ jcambien thanks for the help. I am new to composer

**Comment by jcambien** [comment]
You're welcome :)
Don't forget to close the issue, thanks!

**Comment by vrana** [comment]
Updated, thanks.

**Comment by diimpp** [comment]
Is there reason to have no support for namespaces? Are patches welcome? Same about tests and phpunit

**Comment by vrana** [comment]
The reason for avoiding namespaces is supporting older versions of PHP. I see no reason why to use PHPUnit over PHPT for tests.

**Comment by MightyPork** [comment]
Perhaps it's now time to finally implement namespaces?

They were added in PHP 5.3, which is now at the end of life and not supported anymore, so the argument about old versions is invalid.

**Comment by bensialih** [comment]
hey is there any chance I could set a new repo with everything namespaced?
What youve done with NotORM is some really sterling work. Its just a little hacky for someone that uses namespacing to try and use it.

Bottom line..... really good work just want to make it more useable.

**Comment by vrana** [comment]
Sure, feel free to fork it.
