### ISSUE TITLE
Relations would trigger incorrect column names even when via() was supplied

### ISSUE THREAD

**Issue by itsnotvalid** [vrana/notorm#51]
I fetched a single row from a table with non-standard ID naming. When I try to fetch a related column from another table, I tried to specify the foreign key column name using via('ColumnName'). However the end result of the query would have a where clause with the wrong names in it.
After some investigation the where clause was added right after the creation of the `MultiResult` instance which was returned by the call.
`$return->where("$table.$column", array_keys((array) $this->result->rows));`
There is a problem here because via() is called after this so `$column` in the where clause is always an incorrect value no matter via was set or not.

**Comment by vrana** [comment]
Fixed by #52.
