### ISSUE TITLE
fetchPairs() with column from other table doesn't work

### ISSUE THREAD

**Issue by TomasVotruba** [vrana/notorm#57]
In case I want to get particular user's classroom list from joining table, this returns error:

``` php
$result = $this->db->user_classroom->fetchPairs("classroom.id");
```

_Undefined index: classroom.id_

This would fix it (last foreach in fetchPairs(). But is it ok?

``` php
foreach ($clone as $row) {
    $values = array_values(iterator_to_array($row));
    $return[$values[0]] = ($value != "" ? $values[(isset($values[1]) ? 1 : 0)] : iterator_to_array($row));
}
```

**Comment by vrana** [comment]
It seems that you can use `classroom_id` directly in this case.

**Comment by TomasVotruba** [comment]
Ok. But how to get classroom.name?
