### ISSUE TITLE
allow for switching databases, optimizing tables, running a batch of SQL commands 

### ISSUE THREAD

**Issue by xpavp03** [vrana/notorm#68]
This is a rephrased version of https://github.com/vrana/notorm/issues/64

You've objected to the idea of exposing the PDO connection. I get the point of your counterarguments but that doesn't help me with what I wanted the PDO reference for.

NotORM does only certain things but what if I need more? Was my workaround a real solution then? (To store a reference to PDO myself at the time I give it to NotORM.)

**Comment by xpavp03** [comment]
P.S. Welcome back to the world of the living ;-)

**Comment by vrana** [comment]
Yes. If you need a PDO connection somewhere then pass it there directly. Responsibility of NotORM is not being a container for this connection.

**Comment by xpavp03** [comment]
Sorry but you didn't respond to the point of this (new) issue.
How do I switch databases with NotORM? How do I run OPTIMIZE TABLE? How do I run a batch of SQL queries?

**Comment by vrana** [comment]
The workaround is the real solution.
