### ISSUE TITLE
Weird auto-JOIN create

### ISSUE THREAD

**Issue by bnayal** [vrana/notorm#7]
Hello,
First of all I most say thank you for this great class.
I'm trying to make a query with two "Where" like that:
`$db->table1()->where('last_update > 0 and last_update <= (UNIX_TIMESTAMP()-((avg_days+0.5)*60*60*24))');`
And I get the following SQL statement:
`SELECT table1.* FROM table1 INNER JOIN 0 ON table1.0_id = 0.id WHERE (last_update > 0 and last_update <= (UNIX_TIMESTAMP()-((avg_days+0.5)*60*60*24)))`
It shouldn't insert any JOIN in here.
I went to NotORM/Result.php at line 83 and changed it to:
`if ($name != $this->table and $name != 0) { // case-sensitive`
And it seems to be okay.
But what is the reason for that?

Thanks,
Bnaya Livne

**Comment by vrana** [comment]
You should not pass data inside the query. It is better written as `where('last_update > ? and last_update <= (UNIX_TIMESTAMP()-((avg_days+?)*?))', 0, .5, 60*60*24)`. But I will fix NotORM as well.

**Comment by vrana** [comment]
Stricter identifier detection (closed by 2b9083168166cbcb52466eb697cdeb743ea8de20)

**Comment by bnayal** [comment]
Thanks, I will check it out
