### ISSUE TITLE
[Insight] Usage of a function in loops should be avoided

### ISSUE THREAD

**Issue by antoniogarcia78** [vrana/notorm#76]
**[in NotORM/Result.php, line 453](https://github.com/vrana/notorm/blob/master/NotORM/Result.php#L453)**

> This loop uses a function. To avoid the overhead of executing the function n times, you should precalculate it before the loop.

``` php
                if ($nulls) {
                    $condition = "$condition OR $column IS NULL";
                }
            } else { // http://download.oracle.com/docs/cd/B19306_01/server.102/b14200/expressions014.htm
                $or = array();
                               $numParameters = count($parameters);
                for ($i=0; $i < $numParameters; $i += 1000) {
                    $or[] = "$condition IN " . $this->quote(array_slice($parameters, $i, 1000));
                }
                $condition = implode(" OR ", $or);
            }
        }
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/9810ddf4-ac67-42b8-9d99-4a77e3415514/analyses/1)_

**Comment by vrana** [comment]
Did this cause any performance problem for you? count() in PHP is a very fast function as the number of elements is known.

**Comment by antoniogarcia78** [comment]
No No.It's just a suggestion tool Sensio insights.
I recent discover notORM. I like your approach of multiple select using the primary key.
