### ISSUE TITLE
Hierarchy model behaviour

### ISSUE THREAD

**Issue by alberto-bottarini** [vrana/notorm#85]
Hi, I've got this case:
customers and technicians are both users of my application, but they have different properties except for username and password that allows them to log in.

here are 3 tables I used to represent a basic hierarchy:

TABLE user
COLUMN id, username, password, type (enum customer/technician)

TABLE customer
COLUMN id, user_id,name, vat_number

TABLE technician
COLUMN id, user_id, firstname, lastname

How can I query this structure of tables without becoming crazy? 
Thanks

**Comment by vrana** [comment]
It's not clear what do you mean by "query". For example to get a username of some technician: `$db->technician[$id]->user['username']`.
