### ISSUE TITLE
Stop silencing exceptions

### ISSUE THREAD

**Issue by rk** [vrana/notorm#86]
I've just spend the past 1.5 hours trying to figure out how my script could execute successfully, with no exceptions coming out of my logger on its most verbose setting, and even give import times ... without results being written to MySQL. (It works just fine locally.)

The only way I was able to figure this out was by switching PDO from Exception to Warning error mode.

**Comment by vrana** [comment]
The PDO object passed to NotORM isn't owned by NotORM. You can use it also outside NotORM. NotORM shouldn't affect behaviors of objects not created by it. The correct solution is to configure the PDO object as you wish before passing it to NotORM.

I hate the error reporting modes in PDO as well but NotORM has to respect them.

**Comment by rk** [comment]
Actually, the `NotORM_Result` class _is_ [silencing exceptions](https://github.com/vrana/notorm/blob/master/NotORM/Result.php#L628-L632).

```
            try {
                $result = $this->query($this->__toString(), $parameters);
            } catch (PDOException $exception) {
                // handled later
            }
```

Because that doesn't rethrow the exception, when PDO is in exception error mode no exceptions will be triggered. I had to switch to PDO outputting warnings just to see SQL errors.

**Comment by vrana** [comment]
The exception is rethrown at [line 639](https://github.com/vrana/notorm/blob/073b2e3e74827fbed0e22be73e5a9f952e92f0cd/NotORM/Result.php#L639). If you think it's not the case then please provide a reproducible example.
