### ISSUE TITLE
implicit false if ? is the last character in the where statement

### ISSUE THREAD

**Issue by WooterTheTroubleshooter** [vrana/notorm#87]
Result.php - Line 401 - whereOperator

if ($args != 2 || strpbrk($condition, "?:")) {

strpbrk can return an empty string if ? is the last character which is implicit false.

should be:
if ($args != 2 || strpbrk($condition, "?:") !== false) {

EDIT: I'm new to github and I expected to post an issue next to a file.

**Comment by vrana** [comment]
Please verify bugs before reporting them. `strpbrk` returns the string including the found character.
