### ISSUE TITLE
how to connect MSSQL?????

### ISSUE THREAD

**Issue by hrbwaxdoll** [vrana/notorm#91]
how to change DSN???? 

may by like this?

$dsn = "sqlsrv:Server=127.0.0.1:1433;Database=DatabaseName";
$username = "XXXXX";
$password = "XXXXX";
$pdo = new PDO($dsn, $username, $password);
$db = new NotORM($pdo);

thanks.

**Comment by vrana** [comment]
Consult [PDO documentation](http://php.net/pdo), this is not related to NotORM.

**Comment by hrbwaxdoll** [comment]
thanks！
2014年10月22日 上午12:06于 "Jakub Vrána" notifications@github.com写道：
