### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by harikt** [vrana/notorm#96]
Hi @vrana ,

Hope you are doing good :) .

I wish if you can tag releases, so people don't need to rely on dev-master for it comes with fixes and some backward compatibility changes what ever.

Thank you

**Comment by vrana** [comment]
Release management is a work that I don't want to invest into with NotORM.

**Comment by harikt** [comment]
@vrana isn't it easy as going to https://github.com/vrana/notorm/releases and clicking on adding version and something. I wonder why you think that is hard :( .

**Comment by brandonlamb** [comment]
@harikt :+1:
