### ISSUE TITLE
Need help in fetching data from 3 tables

### ISSUE THREAD

**Issue by nag-uf** [vrana/notorm#98]
The table structure follows:
Table products: id,name
Table categories: id, name
Table locations: id, name
Table product_categories: products_id, categories_id
Table product_locations: products_id, locations_id

Each product can be in multiple categories and multiple locations. I need to fetch products from different categories based on a selected single location id with a limit of 10 records.

Help me to build query with notorm.

**Comment by nag-uf** [comment]
I tried custom query $db->query(); and it is not showing any result. When I run the same query in the MySQL terminal It's giving result. Please let me know how to use custom query method.

The query I have tried was:

$products = $db->query("SELECT DISTINCT(product_categories.products_id) FROM product_categories 
LEFT JOIN products ON product_categories.products_id = products.id 
LEFT JOIN product_locations ON product_locations.products_id=products.id 
WHERE (category_id IN ('3', '4', '5', '9', '17', '18')) AND (products.status = 'Active') AND (product_locations.city_id=1) order by product_categories.products_id ASC LIMIT 10");

foreach($products as $product){
    echo $product['products_id'];
}
No result displayed when using notorm custom query.

**Comment by vrana** [comment]
This isn't a bug. Please use http://groups.google.com/group/notorm for discussion.
